### ISSUE TITLE
IMVDB 4.0.0.0 issue

### ISSUE THREAD

**Issue by gaalos** [jellyfin/jellyfin-plugin-imvdb#23]
Hey i got issues when scanning

Jellyfin server 10.10.1

 ```
 [ERR] Error in IMVDb
2024-11-07T17:37:36.699209+00:00 jelly jellyfin[853415]: System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.results[4].discogs_id | LineNumber: 59 | BytePositionInLine: 30.
2024-11-07T17:37:36.699243+00:00 jelly jellyfin[853415]:  ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
2024-11-07T17:37:36.699268+00:00 jelly jellyfin[853415]:    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedNumber(JsonTokenType tokenType)
2024-11-07T17:37:36.699291+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
2024-11-07T17:37:36.699316+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
2024-11-07T17:37:36.699369+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
2024-11-07T17:37:36.699414+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
2024-11-07T17:37:36.699488+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
2024-11-07T17:37:36.699517+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
2024-11-07T17:37:36.699535+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
2024-11-07T17:37:36.699555+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
2024-11-07T17:37:36.699573+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
2024-11-07T17:37:36.699601+00:00 jelly jellyfin[853415]:    --- End of inner exception stack trace ---
2024-11-07T17:37:36.699649+00:00 jelly jellyfin[853415]:    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
2024-11-07T17:37:36.699671+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
2024-11-07T17:37:36.699691+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
2024-11-07T17:37:36.699713+00:00 jelly jellyfin[853415]:    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
2024-11-07T17:37:36.699734+00:00 jelly jellyfin[853415]:    at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, JsonSerializerOptions options, CancellationToken cancellationToken)
2024-11-07T17:37:36.699754+00:00 jelly jellyfin[853415]:    at Jellyfin.Plugin.IMVDb.ImvdbClient.GetResponseAsync[T](String url, CancellationToken cancellationToken)
2024-11-07T17:37:36.699777+00:00 jelly jellyfin[853415]:    at Jellyfin.Plugin.IMVDb.ImvdbClient.GetSearchResponseAsync(ArtistInfo searchInfo, CancellationToken cancellationToken)
2024-11-07T17:37:36.699797+00:00 jelly jellyfin[853415]:    at Jellyfin.Plugin.IMVDb.Providers.ImvdbArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
2024-11-07T17:37:36.699817+00:00 jelly jellyfin[853415]:    at Jellyfin.Plugin.IMVDb.Providers.ImvdbArtistProvider.GetMetadata(ArtistInfo info, CancellationToken cancellationToken)
2024-11-07T17:37:36.699838+00:00 jelly jellyfin[853415]:    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
 ```

**Comment by Hello-World-Traveler** [comment]
I've notice this myself.

**Comment by IMNdi** [comment]
I think it started after adding an API key
