### ISSUE TITLE
Plugin Not Working on my Jellyfin

### ISSUE THREAD

**Issue by WanKa-zone** [jellyfin/jellyfin-plugin-imvdb#7]
The plugin is not working on my Jellyfin.
No result coming back from the Identify, even filled in the correct IMVDb Id.

![image](https://user-images.githubusercontent.com/45703375/121795395-a22ad500-cc53-11eb-8ec4-39e85bfa2e34.png)

**Comment by crobibero** [comment]
Can you please provide: 
Jellyfin version 
Plugin version 
Server logs

without those I can’t begin to look into this..

**Comment by Eadger** [comment]
> Can you please provide:
> Jellyfin version
> Plugin version
> Server logs
> 
> without those I can’t begin to look into this..

Jellyfin Version: 10.7.5
IMVDb Version: 2.2021.406.2357

[2021-06-13 04:16:40.491 +00:00] [ERR] [49] MediaBrowser.Providers.Manager.ProviderManager: Provider "IMVDb" failed to retrieve search results
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.IMVDb.ImvdbClient.GetSearchResponseAsync(MusicVideoInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.Providers.ImvdbProvider.GetSearchResults(MusicVideoInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2021-06-13 04:16:43.436 +00:00] [INF] [49] Jellyfin.Api.Controllers.MediaInfoController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 384000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264,vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mov", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264", Type: Video }, DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "webm", Type: Video, VideoCodec: "vpx", AudioCodec: "vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: "aac", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline|high 10", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "main", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "120", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }] }
[2021-06-13 04:16:43.438 +00:00] [INF] [49] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "root". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2021-06-13 04:16:43.438 +00:00] [INF] [49] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/media/闊充箰/MV/Girls' Generation - Gee.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-06-13 04:16:43.446 +00:00] [INF] [49] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/media/闊充箰/MV/Girls' Generation - Gee.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-06-13 04:16:43.446 +00:00] [INF] [49] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/media/闊充箰/MV/Girls' Generation - Gee.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2021-06-13 04:16:45.058 +00:00] [WRN] [12] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.238:8096/Sessions/Playing" to "172.17.0.1" in 0:00:00.8631414 with Status Code 204
[2021-06-13 04:16:45.335 +00:00] [INF] [49] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.7.5" playing "Girls' Generation - Gee". Stopped at "555" ms
[2021-06-13 04:16:45.889 +00:00] [WRN] [49] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.238:8096/Sessions/Playing/Stopped" to "172.17.0.1" in 0:00:00.5561815 with Status Code 204
[2021-06-13 04:18:38.952 +00:00] [ERR] [49] MediaBrowser.Providers.Manager.ProviderManager: Provider "IMVDb" failed to retrieve search results
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.IMVDb.ImvdbClient.GetSearchResponseAsync(MusicVideoInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.Providers.ImvdbProvider.GetSearchResults(MusicVideoInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
[2021-06-13 04:18:44.680 +00:00] [WRN] [7] Jellyfin.Networking.Manager.NetworkManager: IPv6 is disabled in Jellyfin, but enabled in the OS. This may affect how the interface is selected.
[2021-06-13 04:19:06.723 +00:00] [INF] [49] Emby.Server.Implementations.ApplicationHost: App needs to be restarted.
[2021-06-13 04:19:18.306 +00:00] [WRN] [23] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.238:8096/Packages?PackageType=UserInstalled" to "172.17.0.1" in 0:00:10.0432718 with Status Code 200
[2021-06-13 04:19:31.397 +00:00] [WRN] [23] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.238:8096/Packages/IMVDb?AssemblyGuid=e29621a5-fa9e-4330-982e-ef6e54c0cad2" to "172.17.0.1" in 0:00:03.570067 with Status Code 200
[2021-06-13 04:19:55.861 +00:00] [INF] [23] Emby.Server.Implementations.Updates.InstallationManager: New plugin installed: "IMVDb" "2.2021.406.2357"
[2021-06-13 04:19:55.867 +00:00] [INF] [23] Emby.Server.Implementations.ApplicationHost: App needs to be restarted.
[2021-06-13 04:19:55.867 +00:00] [WRN] [23] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.238:8096/Packages/Installed/IMVDb?AssemblyGuid=e29621a5-fa9e-4330-982e-ef6e54c0cad2&version=2.2021.406.2357" to "172.17.0.1" in 0:00:04.1823787 with Status Code 204

**Comment by JoaquinMVR** [comment]
![image](https://user-images.githubusercontent.com/11169429/161476204-d5eb72e1-9549-4845-8758-e8f5cbc0692e.png)
![image](https://user-images.githubusercontent.com/11169429/161476329-e588bcda-f4e1-468c-adda-3415af6d392a.png)

Jellyfin: 10.7.7
Operating System: Windows
Architecture: X64

**Comment by Eadger** [comment]
![image](https://user-images.githubusercontent.com/45703375/166820949-834129df-b8c0-4482-9c18-f67465073a5b.png)
It turned to Malfunctioned recently.
![image](https://user-images.githubusercontent.com/45703375/166821067-da957c2b-2aeb-4001-ac0d-f01595a3074a.png)

**Comment by crobibero** [comment]
Unsure where you got v7 from, but v3 is supported on 10.8+

I don't think previous versions are supported

**Comment by Eadger** [comment]
> Unsure where you got v7 from, but v3 is supported on 10.8+
> 
> I don't think previous versions are supported

[12:08:12] [ERR] [24] MediaBrowser.Providers.Manager.ProviderManager: Provider IMVDb failed to retrieve search results                                      
System.NullReferenceException: Object reference not set to an instance of an object.                                                                        
   at Jellyfin.Plugin.IMVDb.ImvdbClient.GetSearchResponseAsync(MusicVideoInfo searchInfo, CancellationToken cancellationToken)                              
   at Jellyfin.Plugin.IMVDb.Providers.ImvdbProvider.GetSearchResults(MusicVideoInfo searchInfo, CancellationToken cancellationToken)                        
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationTok
en cancellationToken)                                                                                                                                       
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, C
ancellationToken cancellationToken)                                                                                                                         
[12:08:12] [ERR] [24] MediaBrowser.Providers.Manager.ProviderManager: Provider YoutubeMetadata failed to retrieve search results                            
System.NotImplementedException: The method or operation is not implemented.                                                                                 
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeRemoteProvider`3.GetSearchResults(E searchInfo, CancellationToken cancellationToken)         
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationTok
en cancellationToken)                                                                                                                                       
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, C
ancellationToken cancellationToken)                                                                                                                         

The plugin I installed, it is a v3.0.0.0.
But I never got a result from Identify section.
![image](https://user-images.githubusercontent.com/45703375/166920248-9cb9092e-7f47-411a-8229-125f507ab396.png)

**Comment by gartner2000** [comment]
same here. in plugin >download > it downloads version 7 and after a reboot it says not supported. delete it and manual install version 3 from here. it finds the plugin and says all ok. but cant get the options in musicvideo to use it as Eadger says.
Using 10.7.7. in unraid docker linuxserver's container.

**Comment by JoaquinMVR** [comment]
The Repositories .json is wrong. 
![image](https://user-images.githubusercontent.com/11169429/173008234-cefde63e-57b3-40f2-89a3-dc1caef904e6.png)
![image](https://user-images.githubusercontent.com/11169429/173008277-1ad6c50e-79f6-4153-98eb-e092b2772acc.png)
That URL redirects to this one: https://tor1.mirror.jellyfin.org/releases/plugin/manifest-stable.json

**Comment by crobibero** [comment]
That's a great find!
I've updated the manifest to remove the offending Gotify release, changes should propagate within the hour

**Comment by crobibero** [comment]
Closing as this should now be fixed. If it is still upgrading please comment here. If it's not working for another reason please open a new issue

**Comment by Eadger** [comment]
Still have no any result come out from Identify section.
![image](https://user-images.githubusercontent.com/45703375/173237650-2df144ef-19b5-46fd-90d1-875a4c25fcc8.png)
Here is the History:
14:14:14] [ERR] [60] MediaBrowser.Providers.Manager.ProviderManager: Provider IMVDb failed to retrieve search results                                      
System.NullReferenceException: Object reference not set to an instance of an object.                                                                        
   at Jellyfin.Plugin.IMVDb.ImvdbClient.GetSearchResponseAsync(MusicVideoInfo searchInfo, CancellationToken cancellationToken)                              
   at Jellyfin.Plugin.IMVDb.Providers.ImvdbProvider.GetSearchResults(MusicVideoInfo searchInfo, CancellationToken cancellationToken)                        
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationTok
en cancellationToken)                                                                                                                                       
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, C
ancellationToken cancellationToken)                                                                                                                         
[14:14:14] [ERR] [60] MediaBrowser.Providers.Manager.ProviderManager: Provider YoutubeMetadata failed to retrieve search results                            
System.NotImplementedException: The method or operation is not implemented.                                                                                 
   at Jellyfin.Plugin.YoutubeMetadata.Providers.AbstractYoutubeRemoteProvider`3.GetSearchResults(E searchInfo, CancellationToken cancellationToken)         
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationTok
en cancellationToken)                                                                                                                                       
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, C
ancellationToken cancellationToken)

**Comment by lyaschuchenko** [comment]
have this error
`[2022-07-18 05:12:56.172 +03:00] [ERR] Error in "IMVDb"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.IMVDb.ImvdbClient.GetResponseAsync[T](String url, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.ImvdbClient.GetSearchResponseAsync(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.Providers.ImvdbArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.Providers.ImvdbArtistProvider.GetMetadata(ArtistInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
`

**Comment by gartner2000** [comment]
Error...

[2022-09-06 04:55:55.548 -07:00] [ERR] [3] MediaBrowser.Providers.Music.MusicVideoMetadataService: Error in "IMVDb"
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.IMVDb.ImvdbClient.GetResponseAsync[T](String url, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.ImvdbClient.GetSearchResponseAsync(MusicVideoInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.Providers.ImvdbProvider.GetSearchResults(MusicVideoInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.Providers.ImvdbProvider.GetMetadata(MusicVideoInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

**Comment by AyrtonB** [comment]
Can confirm I'm getting the same error 

```
[2024-04-21 08:31:49.779 +00:00] [ERR] [29] MediaBrowser.Providers.Manager.ProviderManager: Provider "IMVDb" failed to retrieve search results
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.IMVDb.ImvdbClient.GetSearchResponseAsync(MusicVideoInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.IMVDb.Providers.ImvdbProvider.GetSearchResults(MusicVideoInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
```

**Comment by devNan0** [comment]
Same here

```
Jul 30 20:20:28 jellyfin jellyfin[979]: [20:20:28] [ERR] Provider IMVDb failed to retrieve search results
Jul 30 20:20:28 jellyfin jellyfin[979]: System.NullReferenceException: Object reference not set to an instance of an object.
Jul 30 20:20:28 jellyfin jellyfin[979]:    at Jellyfin.Plugin.IMVDb.ImvdbClient.GetSearchResponseAsync(MusicVideoInfo searchInfo, CancellationToken cancellationToken)
Jul 30 20:20:28 jellyfin jellyfin[979]:    at Jellyfin.Plugin.IMVDb.Providers.ImvdbProvider.GetSearchResults(MusicVideoInfo searchInfo, CancellationToken cancellationToken)
Jul 30 20:20:28 jellyfin jellyfin[979]:    at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)

**Comment by phirestalker** [comment]
I am also getting the Object not set error when attempting to search through identify. I did some other testing. What is essentially searching is working through the automated process, as videos I have in the directory are mostly identified correctly. I can also take one of the misidentified ones and paste in the correct IMVDB id, choose refresh metadata and update missing information, then it gets the correct video info.

**Comment by abrain** [comment]
I've tracked down the problem and will submit a PR shortly.
